
/* Generated by Interface Builder */

#import <objc/List.h>
#import <appkit/Button.h>

#import "HeadButton.h"

@implementation HeadButton

- initFrame:(NXRect *)aFrame
{
	[super initFrame:aFrame];
	buttonList = [List new];
	currentXpos = 0.0;
	return self;
}


- free
{
	[self clear:0.0];
	[buttonList free];
	return [super free];
}


- setTarget:anObject
{
	target = anObject;
	return self;
}


- target
{
	return target;
}


- setAction:(SEL)aSelector
{
	action = aSelector;
	return self;
}


- (SEL)action
{
	return action;
}


- buttonAction:sender
{
	return [target perform:action with:sender];
}


- clear:(float)offsetOfFirstButton
{
	[buttonList makeObjectsPerform:@selector(removeFromSuperview)];
	[[buttonList freeObjects] empty];
	currentXpos = offsetOfFirstButton;
	return self;
}


- addButtonWithTitle:(const char *)title tag:(int)buttonTag andWidth:(float)width
{
	NXRect	aFrame;
	id		aButton;
	
	[self getFrame:&aFrame];
	aFrame.origin.y = 0.0;
	aFrame.origin.x = currentXpos;
	aFrame.size.width = width-1;
	currentXpos += width;
	aButton = [[Button alloc] initFrame:&aFrame];
	[aButton setTitle:title];
	[[aButton setTarget:self] setAction:@selector(buttonAction:)];
	[buttonList addObject:aButton];
	[aButton setTag:buttonTag];
	[self addSubview:aButton];
	return self;
}


- moveToLeft:(int)tag
{
	NXRect	aFrame;
	int 	i,count=[buttonList count];
	BOOL	found=NO;

	[[buttonList objectAt:0] getFrame:&aFrame];
	currentXpos = aFrame.origin.x;
	
	for (i=0;!found && (i<count) ;i++) { 
		if( tag == [[buttonList objectAt:i] tag] ) {
			[buttonList insertObject:[buttonList removeObjectAt:i] at:0];
			found = YES;
		}
	}
	
	if( found ) {
		for(i=0; i<count; i++) {
			[[buttonList objectAt:i] getFrame:&aFrame];
			aFrame.origin.x = currentXpos;
			currentXpos += aFrame.size.width+1.0;
			[[buttonList objectAt:i] setFrame:&aFrame];
		}
	}
	
	[self display];
	
	return self;
}

@end
