
/* Generated by Interface Builder */

#import <appkit/View.h>

@interface HeadButton:View
{
    id		target;
	SEL		action;
	id		buttonList;
	float	currentXpos;
}

- initFrame:(NXRect *)aFrame;
- free;
- setTarget:anObject;
- target;
- setAction:(SEL)aSelector;
- (SEL)action;
- buttonAction:sender;
- clear:(float)offsetOfFirstButton;
- addButtonWithTitle:(const char *)title tag:(int)buttonTag andWidth:(float)width;
- moveToLeft:(int)tag;

@end
