
/* Generated by Interface Builder */

#import <appkit/Control.h>

@interface TimerView:Control
{
	double myDouble;
}
- reset;
- drawSelf:(NXRect *)rects :(int ) count;
- setDoubleValue:(double )aValue;
- (double )doubleValue;
@end
